# Generated by Django 6.0.4 on 2026-06-08 12:43

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="status_changed",
            field=model_utils.fields.MonitorField(
                default=django.utils.timezone.now,
                monitor="status",
                verbose_name="status changed",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="status",
            field=model_utils.fields.StatusField(
                choices=[
                    ("PENDING", "Pending"),
                    ("SENT", "Sent"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                max_length=100,
                no_check_for_status=True,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("EMAIL_CONFIRMATION", "Email Confirmation"),
                    ("DOCUMENT_REQUEST", "Document Request"),
                    ("REMINDER", "Reminder"),
                    ("SYSTEM", "System"),
                ],
                default="EMAIL_CONFIRMATION",
                max_length=30,
            ),
        ),
    ]
