# Generated by Django 6.0.4 on 2026-06-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_notification_status_changed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("EMAIL_CONFIRMATION", "Email Confirmation"),
                    ("DOCUMENT_REQUEST", "Document Request"),
                    ("REMINDER", "Reminder"),
                ],
                default="EMAIL_CONFIRMATION",
                max_length=30,
            ),
        ),
    ]
