# Generated by Django 6.0.4 on 2026-05-13 11:30

from django.db import migrations, models

import app.apps.accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_emailconfirmation"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=app.apps.accounts.models.avatar_upload_path,
            ),
        ),
    ]
