# Generated by Django 6.0.4 on 2026-08-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_registration_method_socialaccount"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_blocked",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="socialaccount",
            name="provider",
            field=models.CharField(choices=[("GOOGLE", "Google")], max_length=20),
        ),
        migrations.AlterField(
            model_name="user",
            name="registration_method",
            field=models.CharField(
                choices=[("EMAIL", "Email"), ("GOOGLE", "Google")],
                default="EMAIL",
                max_length=20,
            ),
        ),
    ]
