# Generated by Django 6.0.4 on 2026-08-27 20:40

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_is_blocked_alter_socialaccount_provider_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_2fa_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether two-factor authentication is enabled for this user",
                verbose_name="Is 2FA enabled",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_confirmed",
            field=models.BooleanField(
                default=False,
                help_text="Whether phone_number has been verified via SMS code",
                verbose_name="Phone confirmed",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="Phone number for SMS-based 2FA",
                max_length=32,
                null=True,
                verbose_name="Phone number",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="two_factor_method",
            field=models.CharField(
                choices=[("EMAIL", "Email"), ("SMS", "SMS")],
                default="EMAIL",
                help_text="Primary two-factor authentication channel",
                max_length=20,
                verbose_name="2FA Method",
            ),
        ),
        migrations.CreateModel(
            name="PhoneConfirmation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        help_text="The phone number this confirmation attempt is for",
                        max_length=32,
                        verbose_name="Phone number",
                    ),
                ),
                ("code_hash", models.CharField(max_length=64)),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Expiration time for the confirmation code",
                        verbose_name="Expires at",
                    ),
                ),
                ("is_confirmed", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phone_confirmations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("is_revoked", models.BooleanField(default=False)),
                (
                    "device_token_hash",
                    models.CharField(
                        db_index=True,
                        help_text="SHA-256 hash of the unique device identification token",
                        max_length=64,
                        verbose_name="Device token hash",
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True,
                        help_text="User-Agent browser string associated with the device",
                        max_length=512,
                        verbose_name="User agent",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="Last recorded IP address of the device",
                        null=True,
                        verbose_name="IP address",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Expiration timestamp for the trusted device session",
                        verbose_name="Expires at",
                    ),
                ),
                (
                    "last_login_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of the last successful authentication from this device",
                        null=True,
                        verbose_name="Last login at",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="City and country resolved from IP address",
                        max_length=255,
                        verbose_name="Location",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User owning this trusted device",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "User device",
                "verbose_name_plural": "User devices",
                "ordering": ["-last_login_at"],
            },
        ),
    ]
