# Generated by Django 6.0.4 on 2026-05-27 09:05

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="document",
            options={
                "ordering": ["-created"],
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
            },
        ),
        migrations.AlterModelOptions(
            name="documentrequest",
            options={
                "ordering": ["-created"],
                "verbose_name": "Document request",
                "verbose_name_plural": "Document requests",
            },
        ),
        migrations.AlterModelOptions(
            name="documenttype",
            options={
                "ordering": ["name"],
                "verbose_name": "Document type",
                "verbose_name_plural": "Document types",
            },
        ),
        migrations.RemoveField(
            model_name="document",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="document",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="documentrequest",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="documenttype",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="documenttype",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="document",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="created",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="modified",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="status_changed",
            field=model_utils.fields.MonitorField(
                default=django.utils.timezone.now,
                monitor="status",
                verbose_name="status changed",
            ),
        ),
        migrations.AddField(
            model_name="documentrequest",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="created",
            ),
        ),
        migrations.AddField(
            model_name="documentrequest",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="modified",
            ),
        ),
        migrations.AddField(
            model_name="documentrequest",
            name="status_changed",
            field=model_utils.fields.MonitorField(
                default=django.utils.timezone.now,
                monitor="status",
                verbose_name="status changed",
            ),
        ),
        migrations.AddField(
            model_name="documenttype",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="created",
            ),
        ),
        migrations.AddField(
            model_name="documenttype",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="modified",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="expiration_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Expiration date"
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="status",
            field=model_utils.fields.StatusField(
                choices=[("ACTIVE", "Active"), ("REPLACED", "Replaced")],
                default="ACTIVE",
                max_length=100,
                no_check_for_status=True,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="documentrequest",
            name="document_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="document_requests",
                to="documents.documenttype",
                verbose_name="Document type",
            ),
        ),
        migrations.AlterField(
            model_name="documentrequest",
            name="expires_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Expires at"
            ),
        ),
        migrations.AlterField(
            model_name="documentrequest",
            name="status",
            field=model_utils.fields.StatusField(
                choices=[
                    ("PENDING", "Pending"),
                    ("COMPLETED", "Completed"),
                    ("CANCELED", "Canceled"),
                    ("EXPIRED", "Expired"),
                ],
                default="PENDING",
                max_length=100,
                no_check_for_status=True,
                verbose_name="status",
            ),
        ),
    ]
