# Generated by Django 6.0.4 on 2026-05-30 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "documents",
            "0002_alter_document_options_alter_documentrequest_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="documents.documenttype",
                verbose_name="Document type",
            ),
        ),
    ]
