# Generated by Django 6.0.4 on 2026-06-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0004_alter_document_document_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="is_reminder_sent",
            field=models.BooleanField(default=False, verbose_name="Is Reminder Sent"),
        ),
    ]
