# Generated by Django 6.0.4 on 2026-07-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_stripewebhookevent_alter_subscription_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="stripewebhookevent",
            name="event_type",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stripewebhookevent",
            name="processed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="stripewebhookevent",
            name="processed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
