# Generated by Django 6.0.4 on 2026-07-24 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_stripewebhookevent_event_type_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StripeWebhookEvent",
        ),
    ]
