# Generated by Django 6.0.4 on 2026-08-04 08:36

# app/apps/billing/migrations/0006_seed_default_plans.py

from django.db import migrations


def create_default_plans(apps, schema_editor):
    Plan = apps.get_model("billing", "Plan")
    Plan.objects.get_or_create(
        name="FREE",
        defaults={
            "description": "Free plan",
            "document_limit": 5,
            "price": 0,
            "is_active": True,
        },
    )


def remove_default_plans(apps, schema_editor):
    Plan = apps.get_model("billing", "Plan")
    Plan.objects.filter(name="FREE").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0005_delete_stripewebhookevent"),
    ]

    operations = [
        migrations.RunPython(create_default_plans, remove_default_plans),
    ]
